name: "DH Lottery Auto"
version: "0.1.2"
slug: "dh_lottery_auto"
description: "Buy DH Lottery tickets on a schedule and expose results to Home Assistant."
startup: application
init: false
arch:
  - amd64
map:
  - type: homeassistant_config
    read_only: false
    path: /homeassistant
options:
  dhlottery_id: ""
  dhlottery_pw: ""
  games_per_purchase: 5
  interval_days: 7
schema:
  dhlottery_id: str
  dhlottery_pw: password
  telegram_bot_token: password?
  telegram_chat_id: str?
  games_per_purchase: int(1,5)
  interval_days: int(1,)
